spring.application.name=proyecto-reserva-service
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:mysql://localhost:3306/db_reserva?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest



resilience4j.circuitbreaker.instances.aula-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.aula-service.slidingWindowSize=5
resilience4j.circuitbreaker.instances.aula-service.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.aula-service.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.aula-service.automaticTransitionFromOpenToHalfOpenEnabled=true



resilience4j.circuitbreaker.instances.servicio-usuarios.failureRateThreshold=50
resilience4j.circuitbreaker.instances.servicio-usuarios.slidingWindowSize=5
resilience4j.circuitbreaker.instances.servicio-usuarios.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.servicio-usuarios.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.servicio-usuarios.automaticTransitionFromOpenToHalfOpenEnabled=true